### ISSUE TITLE
Missing Tags

### ISSUE THREAD

**Issue by jade-42** [ric03uec/nodeblox#5]
> The tags in 'master' branch refer to the corresponding tutorial versions

The ReadMe points to the tag in the 'master' branch. But Github claims that there aren't any [tags](https://github.com/ric03uec/nodeblox/tags) in the repository.

**Comment by ric03uec** [comment]
fixed. tags are now visible in the repository.

**Comment by jade-42** [comment]
Thanks, and thanks for a great tutorial and starting template.
